variables: 
  GRADLE_OPTS: "-Dorg.gradle.daemon=false"
  GIT_STRATEGY: clone  

before_script: 
  - echo "Build, Test, Deploy"

stages:
  - build
  - test
  - deploy

Build:
  image: eclipse-temurin:17-jdk
  stage: build
  tags:
    - dalfcs_gitlab_docker_ci
  script:
    - echo "Building"
    - ./gradlew build

Test: 
  image: eclipse-temurin:17-jdk
  stage: test
  tags:
    - dalfcs_gitlab_docker_ci
  script:
    - echo "Testing"
    - ./gradlew test
  artifacts:
    when: always
    reports:
      junit: build/test-results/test/TEST-*.xml

Deploy:
  image: openjdk:17-jdk-buster
  stage: deploy
  tags:
    - dalfcs_gitlab_docker_ci
  only:
    - main
  script:
    - apt-get update -qy
    - apt-get install -y ruby-dev
    - gem install dpl
    - dpl --provider=heroku --app=$HEROKU_APP_STAGING --api-key=$HEROKU_API_KEY
    #- apt-get update
    #- apt-get install -y git
    #- git remote add heroku https://heroku:$HEROKU_API_KEY@git.heroku.com/gradle-project.git
    #- git push -f heroku HEAD:main

after_script: 
  - echo "This Works!!!"
